build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
labels:
  io.hass.name: "Braiins Manager Agent"
  io.hass.description: "Braiins Manager Agent for Home Assistant"
  io.hass.type: addon