---
name: "Braiins Manager Agent"
version: "4.1.4"
slug: "braiins-manager-agent"
description: "Remotely manage and monitor your mining hardware through the Braiins Manager platform"
url: "https://github.com/Donach/ha-addons/tree/main/braiins-manager-agent"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
host_network: true
options:
  agent_id: ""
  secret_key: ""
  logging:
    level: "info"
schema:
  agent_id: str
  secret_key: str
  logging:
    level: str
image: "ghcr.io/donach/braiins-manager-agent-{arch}"