---
name: "Braiins Manager Agent"
version: "4.1.1"
slug: "braiins-manager-agent"
description: "Remotely manage and monitor your mining hardware through the Braiins Manager platform"
url: https://braiins.com/manager
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
host_network: true
options:
  agent_id: ""
  secret_key: ""
schema:
  agent_id: str
  secret_key: str
image: "ghcr.io/donach/braiins-manager-agent-{arch}"