name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, aarch64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare version
        id: version
        run: |
          version=$(cat braiins-manager-agent/config.yaml | grep version | awk '{print $2}' | tr -d '"')
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./braiins-manager-agent
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/${{ matrix.arch }}
          tags: ghcr.io/donach/braiins-manager-agent-${{ matrix.arch }}:${{ steps.version.outputs.version }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.arch }}-base:latest
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            BUILD_DESCRIPTION="Braiins Manager Agent for Home Assistant"
            BUILD_NAME="Braiins Manager Agent"
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_VERSION=${{ steps.version.outputs.version }}